/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROL.UsuarioDAO;
import CONTROL.UsuarioInfoDAO;
import MODELO.*;

/**
 *
 * @author estudiante307
 */
public class FotosFamGUI extends javax.swing.JDialog {

    /**
     * Creates new form FotosFamGUI
     */
    public FotosFamGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
        userName.setText("Usuario: " + MainApp.logname);
        UsuarioDAO udao = new UsuarioDAO();
        Usuario u = udao.obtenerUsuarioPorUser(MainApp.logname);
        UsuarioInfoDAO uidao = new UsuarioInfoDAO();
        UsuarioInfo ui = uidao.obtenerUsuarioInfoPorId(MainApp.logid);
        cargarFoto(u.getCarpeta(), u.getNameFile());
        areaNombre.setText(ui.getName());
        areaApellido.setText(ui.getApellido());
        areaSexo.setText(ui.getSexo()+"");
        areaEmail.setText(ui.getEmail());
        areaEdad.setText(ui.getEdad()+"");
        areaCarpeta.setText(ui.getCarpeta());
        areaNameFile.setText(MainApp.logname+".jpg");
    }
    
    public void cargarFoto(String carpeta, String fileName){
        userPhoto.setIcon(new javax.swing.ImageIcon(carpeta+fileName));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        barrainferior = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        iconTitle = new javax.swing.JLabel();
        photosEspacio = new javax.swing.JPanel();
        textName = new javax.swing.JLabel();
        areaNombre = new javax.swing.JTextField();
        textApellido = new javax.swing.JLabel();
        areaApellido = new javax.swing.JTextField();
        textSexo = new javax.swing.JLabel();
        areaSexo = new javax.swing.JTextField();
        textEmail = new javax.swing.JLabel();
        areaEmail = new javax.swing.JTextField();
        textFolder = new javax.swing.JLabel();
        areaCarpeta = new javax.swing.JTextField();
        textNamePhoto = new javax.swing.JLabel();
        areaNameFile = new javax.swing.JTextField();
        textParentesco = new javax.swing.JLabel();
        areaParen = new javax.swing.JTextField();
        btnFirts = new javax.swing.JPanel();
        btnLast = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        userName = new javax.swing.JLabel();
        bgPhotoUser = new javax.swing.JPanel();
        userPhoto = new javax.swing.JLabel();
        textEdad = new javax.swing.JLabel();
        areaEdad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barrainferior.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout barrainferiorLayout = new javax.swing.GroupLayout(barrainferior);
        barrainferior.setLayout(barrainferiorLayout);
        barrainferiorLayout.setHorizontalGroup(
            barrainferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        barrainferiorLayout.setVerticalGroup(
            barrainferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        bg.add(barrainferior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1068, -1));

        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setText("Informacion Familiar");
        bg.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 11, 275, 41));

        iconTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VISTA/Images/familyIcon.png"))); // NOI18N
        bg.add(iconTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 11, -1, -1));

        photosEspacio.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout photosEspacioLayout = new javax.swing.GroupLayout(photosEspacio);
        photosEspacio.setLayout(photosEspacioLayout);
        photosEspacioLayout.setHorizontalGroup(
            photosEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        photosEspacioLayout.setVerticalGroup(
            photosEspacioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        bg.add(photosEspacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 91, -1, -1));

        textName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        textName.setText("Nombre: ");
        bg.add(textName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, 25));

        areaNombre.setEditable(false);
        areaNombre.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        areaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaNombreActionPerformed(evt);
            }
        });
        bg.add(areaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 100, -1));

        textApellido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        textApellido.setText("Apellido:");
        bg.add(textApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 51, -1));

        areaApellido.setEditable(false);
        areaApellido.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        bg.add(areaApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 100, -1));

        textSexo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        textSexo.setText("Sexo:");
        bg.add(textSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 51, 20));

        areaSexo.setEditable(false);
        areaSexo.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        bg.add(areaSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 30, -1));

        textEmail.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        textEmail.setText("Email:");
        bg.add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 41, 20));

        areaEmail.setEditable(false);
        areaEmail.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        bg.add(areaEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 200, -1));

        textFolder.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        textFolder.setText("Carpeta: ");
        bg.add(textFolder, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));

        areaCarpeta.setEditable(false);
        areaCarpeta.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        bg.add(areaCarpeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 190, -1));

        textNamePhoto.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        textNamePhoto.setText("Nombre Foto:");
        bg.add(textNamePhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        areaNameFile.setEditable(false);
        areaNameFile.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        bg.add(areaNameFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 92, -1));

        textParentesco.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        textParentesco.setText("Parentesco:");
        bg.add(textParentesco, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        areaParen.setEditable(false);
        areaParen.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        bg.add(areaParen, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 92, -1));

        javax.swing.GroupLayout btnFirtsLayout = new javax.swing.GroupLayout(btnFirts);
        btnFirts.setLayout(btnFirtsLayout);
        btnFirtsLayout.setHorizontalGroup(
            btnFirtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        btnFirtsLayout.setVerticalGroup(
            btnFirtsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bg.add(btnFirts, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 301, -1, 45));

        javax.swing.GroupLayout btnLastLayout = new javax.swing.GroupLayout(btnLast);
        btnLast.setLayout(btnLastLayout);
        btnLastLayout.setHorizontalGroup(
            btnLastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        btnLastLayout.setVerticalGroup(
            btnLastLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bg.add(btnLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 301, -1, 45));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(799, 301, -1, 45));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        bg.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(854, 301, -1, -1));

        userName.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        userName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg.add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(819, 11, 220, 31));

        bgPhotoUser.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout bgPhotoUserLayout = new javax.swing.GroupLayout(bgPhotoUser);
        bgPhotoUser.setLayout(bgPhotoUserLayout);
        bgPhotoUserLayout.setHorizontalGroup(
            bgPhotoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
        );
        bgPhotoUserLayout.setVerticalGroup(
            bgPhotoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );

        bg.add(bgPhotoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 50, 135, 180));

        textEdad.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        textEdad.setText("Edad:");
        bg.add(textEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 40, 20));

        areaEdad.setEditable(false);
        areaEdad.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        bg.add(areaEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 40, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FotosFamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FotosFamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FotosFamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FotosFamGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FotosFamGUI dialog = new FotosFamGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaApellido;
    private javax.swing.JTextField areaCarpeta;
    private javax.swing.JTextField areaEdad;
    private javax.swing.JTextField areaEmail;
    private javax.swing.JTextField areaNameFile;
    private javax.swing.JTextField areaNombre;
    private javax.swing.JTextField areaParen;
    private javax.swing.JTextField areaSexo;
    private javax.swing.JPanel barrainferior;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgPhotoUser;
    private javax.swing.JPanel btnFirts;
    private javax.swing.JPanel btnLast;
    private javax.swing.JLabel iconTitle;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel photosEspacio;
    private javax.swing.JLabel textApellido;
    private javax.swing.JLabel textEdad;
    private javax.swing.JLabel textEmail;
    private javax.swing.JLabel textFolder;
    private javax.swing.JLabel textName;
    private javax.swing.JLabel textNamePhoto;
    private javax.swing.JLabel textParentesco;
    private javax.swing.JLabel textSexo;
    private javax.swing.JLabel title;
    private javax.swing.JLabel userName;
    private javax.swing.JLabel userPhoto;
    // End of variables declaration//GEN-END:variables
}
